### ISSUE TITLE
src/dataweb/web: Uncaught Error: Cannot find module './packages/index'

### ISSUE THREAD

**Issue by Levix** [Tencent/bk-base#9]
**What happened**:
根据 `src/dataweb/web` README 文档相关配置完毕后，其中也执行了 `npm run init-extend` 命令，成功 link 到了 `src/extends/packages` 文件夹下，但运行项目后出现 `Uncaught Error: Cannot find module './packages/index'` 错误。

问题出现在 `src\extends\index.ts` 文件 `const packages = require('./packages/index');`

**What you expected to happen**:

`packages/index` 该文件是怎样的？希望能得到回复。

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-base version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wking1986** [comment]
目前bk-base编译安装还有些问题，我们正在解决和优化，感谢您对bk-base的关注～
